"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import toast from "react-hot-toast";

export default function ReservationTables({ reservationId, covers, initialTables, initialAssignedIds, active }: { reservationId: string; covers: number; initialTables: { id: string; number: string; capacity: number; zone: string; status: string }[]; initialAssignedIds: string[]; active: boolean }) {
  const router = useRouter(); const [assigned, setAssigned] = useState(initialAssignedIds); const [loading, setLoading] = useState(false);
  const totalCapacity = useMemo(() => initialTables.filter((t) => assigned.includes(t.id)).reduce((sum, t) => sum + t.capacity, 0), [assigned, initialTables]);
  const toggle = (id: string) => setAssigned((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  const save = async () => { setLoading(true); try { const res = await fetch(`/api/admin/reservations/${reservationId}/tables`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tableIds: assigned }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); toast.success("Tables attribuées"); router.refresh(); } catch (e) { toast.error((e as Error).message); } finally { setLoading(false); } };
  return <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="font-display text-xl text-[#F5F0EB]">Tables attribuées</h2><p className="text-xs text-[#5A5249] mt-1">{assigned.length ? `${assigned.length} table(s) · ${totalCapacity} places pour ${covers} couvert(s)` : "Aucune table attribuée"}</p></div><span className={`text-xs px-2 py-1 rounded-full ${totalCapacity >= covers ? "bg-emerald-500/10 text-emerald-400" : "bg-yellow-500/10 text-yellow-400"}`}>{totalCapacity >= covers ? "Capacité OK" : "Capacité insuffisante"}</span></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{initialTables.map((table) => { const selected = assigned.includes(table.id); const disabled = !active || table.status === "OUT_OF_SERVICE"; return <button type="button" key={table.id} disabled={disabled} onClick={() => toggle(table.id)} className={`text-left p-3 rounded-xl border transition-colors ${selected ? "border-[#C8973A] bg-[#C8973A]/10" : "border-[#222] bg-[#0A0A0A] hover:border-[#333]"} ${disabled ? "opacity-35 cursor-not-allowed" : ""}`}><p className="text-sm font-medium text-[#F5F0EB]">Table {table.number}</p><p className="text-xs text-[#5A5249] mt-1">{table.capacity} places · {table.zone}</p>{table.status === "OUT_OF_SERVICE" && <p className="text-[10px] text-red-400 mt-1">Hors service</p>}</button>; })}</div><Button className="w-full mt-5" onClick={save} loading={loading} disabled={!active || totalCapacity < covers}>Enregistrer l&apos;attribution</Button><p className="text-[11px] text-[#5A5249] mt-3 leading-relaxed">Deux réservations peuvent utiliser la même table à des horaires différents. Le système vérifie automatiquement les chevauchements selon la durée de service configurée.</p></div>;
}
