"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Armchair, CheckCircle2, Minus, Plus, Receipt, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import { formatPrice } from "@/lib/utils";

type Dish = { id: string; name: string; price: number; category: string; categoryOrder: number; order: number };
type Table = { id: string; number: string; capacity: number; zone: string; status: string };
type Item = { id: string; dishId: string | null; name: string; unitPrice: number; quantity: number; lineTotal: number; notes: string | null };
type Order = { id: string; reservationId: string | null; guestFirstName: string | null; guestLastName: string | null; guestPhone: string | null; covers: number; status: string; notes: string | null; subtotal: number; discountAmount: number; totalAmount: number; depositApplied: number; paidAmount: number; dueAmount: number; openedAt: string; reservation: { id: string; guestFirstName: string; guestLastName: string; date: string; timeSlot: string; deposit: number } | null; tables: { id: string; number: string }[]; items: Item[]; payments: { id: string; amount: number; method: string; reference: string | null; paidAt: string }[] };

const statuses = [{ value: "OPEN", label: "En cours" }, { value: "SUBMITTED", label: "Envoyée" }, { value: "PREPARING", label: "En préparation" }, { value: "READY", label: "Prête" }, { value: "SERVED", label: "Servie" }];

export default function OrderDetailClient({ initialOrder, dishes, tables }: { initialOrder: Order; dishes: Dish[]; tables: Table[] }) {
  const router = useRouter(); const [order, setOrder] = useState(initialOrder); const [items, setItems] = useState<Item[]>(initialOrder.items); const [discount, setDiscount] = useState(String(initialOrder.discountAmount)); const [notes, setNotes] = useState(initialOrder.notes ?? ""); const [tableIds, setTableIds] = useState<string[]>(initialOrder.tables.map((x) => x.id)); const [loading, setLoading] = useState(false); const [paying, setPaying] = useState(false); const [paymentAmount, setPaymentAmount] = useState(String(initialOrder.dueAmount)); const [paymentMethod, setPaymentMethod] = useState("CARD");
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0), [items]);
  const total = Math.max(0, subtotal - Math.max(0, Number(discount) || 0));
  const active = ["OPEN", "SUBMITTED", "PREPARING", "READY", "SERVED"].includes(order.status);
  const toggleTable = (id: string) => setTableIds((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  const addDish = (dish: Dish) => setItems((current) => { const existing = current.find((x) => x.dishId === dish.id); if (existing) return current.map((x) => x.dishId === dish.id ? { ...x, quantity: x.quantity + 1, lineTotal: (x.quantity + 1) * x.unitPrice } : x); return [...current, { id: `new-${dish.id}-${Date.now()}`, dishId: dish.id, name: dish.name, unitPrice: dish.price, quantity: 1, lineTotal: dish.price, notes: null }]; });
  const changeQty = (itemId: string, delta: number) => setItems((current) => current.map((x) => x.id === itemId ? { ...x, quantity: x.quantity + delta, lineTotal: (x.quantity + delta) * x.unitPrice } : x).filter((x) => x.quantity > 0));
  const save = async (status?: string) => { setLoading(true); try { const res = await fetch(`/api/admin/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map((x) => ({ dishId: x.dishId, quantity: x.quantity, notes: x.notes })), discountAmount: Number(discount) || 0, notes, tableIds, ...(status ? { status } : {}) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); toast.success(status === "PAID" ? "Addition réglée" : "Commande enregistrée"); setOrder((current) => ({ ...current, ...data.data })); router.refresh(); } catch (e) { toast.error((e as Error).message); } finally { setLoading(false); } };
  const pay = async () => { const amount = Number(paymentAmount); if (!amount || amount <= 0) return toast.error("Montant invalide"); setPaying(true); try { const res = await fetch(`/api/admin/orders/${order.id}/payments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, method: paymentMethod }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); toast.success("Règlement enregistré"); setOrder((current) => ({ ...current, ...data.data })); setPaymentAmount(""); router.refresh(); } catch (e) { toast.error((e as Error).message); } finally { setPaying(false); } };
  const statusLabel = statuses.find((s) => s.value === order.status)?.label ?? (order.status === "PAID" ? "Réglée" : order.status === "CANCELLED" ? "Annulée" : order.status);
  return <div>
    <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4 mb-6"><div><p className="text-xs uppercase tracking-[0.18em] text-[#C8973A] mb-2">Addition #{order.id.slice(-8).toUpperCase()}</p><h1 className="font-display text-3xl text-[#F5F0EB]">{order.guestFirstName || "Client sur place"} {order.guestLastName || ""}</h1><p className="text-sm text-[#5A5249] mt-1">{order.reservation ? `Réservation · ${order.reservation.timeSlot}` : "Arrivée directe · sans réservation"} · {order.covers} couvert{order.covers > 1 ? "s" : ""}</p></div><Badge variant={order.status === "PAID" ? "green" : order.status === "CANCELLED" ? "red" : "yellow"} className="text-base px-4 py-1.5">{statusLabel}</Badge></div>
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_390px] gap-6"><div className="space-y-6">
      {order.reservation && <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-xl p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-emerald-400 mb-1">Acompte de réservation</p><p className="text-sm text-[#F5F0EB]">{formatPrice(order.reservation.deposit)} déjà payé</p></div><CheckCircle2 size={18} className="text-emerald-400" /></div><p className="text-xs text-[#9A8F84] mt-2">Seule la part réellement applicable à cette addition est déduite. Un acompte remboursé n'est jamais imputé.</p></div>}
      <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><div className="flex items-center gap-2 mb-4"><Armchair size={18} className="text-[#C8973A]" /><h2 className="font-display text-xl text-[#F5F0EB]">Tables</h2></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{tables.map((table) => { const assignedToThisReservation = !order.reservationId || order.reservation ? true : false; const selected = tableIds.includes(table.id); const allowed = assignedToThisReservation && (table.status === "AVAILABLE" || selected); return <button type="button" disabled={!active || !allowed} onClick={() => toggleTable(table.id)} key={table.id} className={`p-3 rounded-xl border text-left ${selected ? "border-[#C8973A] bg-[#C8973A]/10" : "border-[#222] bg-[#0A0A0A]"} ${!allowed ? "opacity-30" : ""}`}><p className="text-sm text-[#F5F0EB]">Table {table.number}</p><p className="text-xs text-[#5A5249] mt-1">{table.capacity} places · {table.zone}</p></button>; })}</div><p className="text-[11px] text-[#5A5249] mt-3">Pour une réservation, les tables doivent rester celles qui lui sont attribuées dans la fiche réservation.</p></div>
      <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><h2 className="font-display text-xl text-[#F5F0EB] mb-4">Articles</h2><div className="space-y-3">{items.map((item) => <div key={item.id} className="flex items-center gap-3 border-b border-[#222] pb-3"><div className="flex-1"><p className="text-sm text-[#F5F0EB]">{item.name}</p><p className="text-xs text-[#5A5249]">{formatPrice(item.unitPrice)} / unité</p></div><button type="button" disabled={!active} onClick={() => changeQty(item.id, -1)} className="w-7 h-7 bg-[#222] rounded flex items-center justify-center text-[#9A8F84]"><Minus size={13} /></button><span className="w-5 text-center text-sm text-[#F5F0EB]">{item.quantity}</span><button type="button" disabled={!active} onClick={() => changeQty(item.id, 1)} className="w-7 h-7 bg-[#222] rounded flex items-center justify-center text-[#9A8F84]"><Plus size={13} /></button><span className="w-20 text-right text-sm text-[#F5F0EB]">{formatPrice(item.lineTotal)}</span><button type="button" disabled={!active} onClick={() => setItems((current) => current.filter((x) => x.id !== item.id))} className="text-[#5A5249] hover:text-red-400"><Trash2 size={14} /></button></div>)}</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-5">{dishes.map((dish) => <button type="button" disabled={!active} onClick={() => addDish(dish)} key={dish.id} className="text-left p-3 rounded-lg border border-[#222] hover:border-[#C8973A]/30"><p className="text-sm text-[#F5F0EB]">{dish.name}</p><p className="text-xs text-[#C8973A] mt-1">{formatPrice(dish.price)}</p></button>)}</div></div>
      <div className="bg-[#141414] border border-[#222] rounded-xl p-6 space-y-4"><Textarea label="Notes" value={notes} onChange={(e) => setNotes(e.target.value)} disabled={!active} /><div className="grid grid-cols-2 gap-4"><Input label="Remise (€)" type="number" step="0.01" min="0" value={discount} onChange={(e) => setDiscount(e.target.value)} disabled={!active} /><Input label="Reste calculé" value={formatPrice(total - order.depositApplied - order.paidAmount)} readOnly /></div><Button onClick={() => save()} loading={loading} disabled={!active} className="w-full">Enregistrer les modifications</Button></div>
    </div><div className="space-y-6 xl:sticky xl:top-6 h-fit"><div className="bg-[#141414] border border-[#222] rounded-xl p-6"><div className="flex items-center gap-2 mb-5"><Receipt size={18} className="text-[#C8973A]" /><h2 className="font-display text-xl text-[#F5F0EB]">Addition finale</h2></div><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#9A8F84]">Sous-total</span><span className="text-[#F5F0EB]">{formatPrice(subtotal)}</span></div><div className="flex justify-between"><span className="text-[#9A8F84]">Remise</span><span className="text-[#F5F0EB]">-{formatPrice(Math.max(0, Number(discount) || 0))}</span></div><div className="border-t border-[#222] pt-3 flex justify-between"><span className="text-[#F5F0EB] font-medium">Total</span><span className="text-[#C8973A] font-display text-xl">{formatPrice(total)}</span></div><div className="flex justify-between"><span className="text-emerald-400">Acompte imputé</span><span className="text-emerald-400">-{formatPrice(order.depositApplied)}</span></div><div className="flex justify-between"><span className="text-[#9A8F84]">Déjà encaissé sur place</span><span className="text-[#F5F0EB]">-{formatPrice(order.paidAmount)}</span></div><div className="border-t border-[#222] pt-3 flex justify-between"><span className="text-[#F5F0EB] font-medium">Reste à payer</span><span className="text-[#C8973A] font-display text-2xl">{formatPrice(Math.max(0, total - order.depositApplied - order.paidAmount))}</span></div></div></div>
      {active && <div className="bg-[#141414] border border-[#222] rounded-xl p-6 space-y-3"><h2 className="font-display text-lg text-[#F5F0EB]">Encaisser</h2><Input label="Montant (€)" type="number" step="0.01" min="0.01" value={paymentAmount} onChange={(e) => setPaymentAmount(e.target.value)} /><Select label="Mode" value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value)} options={[{ value: "CARD", label: "Carte bancaire" }, { value: "CASH", label: "Espèces" }, { value: "CHEQUE", label: "Chèque" }, { value: "OTHER", label: "Autre" }]} /><Button onClick={pay} loading={paying} className="w-full">Enregistrer le règlement</Button></div>}
      {active && <div className="bg-[#141414] border border-[#222] rounded-xl p-6 space-y-2"><h2 className="font-display text-lg text-[#F5F0EB]">Flux de service</h2>{statuses.map((status) => <Button key={status.value} disabled={status.value === order.status || !active} variant={status.value === order.status ? "primary" : "secondary"} size="sm" className="w-full" onClick={() => save(status.value)}>{status.label}</Button>)}<Button variant="destructive" size="sm" className="w-full" onClick={() => save("CANCELLED")}>Annuler la commande</Button></div>}
      {order.payments.length > 0 && <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><h2 className="font-display text-lg text-[#F5F0EB] mb-3">Règlements</h2><div className="space-y-2">{order.payments.map((p) => <div key={p.id} className="flex justify-between text-xs"><span className="text-[#9A8F84]">{p.method}</span><span className="text-[#F5F0EB]">{formatPrice(p.amount)}</span></div>)}</div></div>}
    </div></div>
  </div>;
}
