"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { UserRound, Armchair, Plus, Minus, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import { getErrorMessage, formatPrice } from "@/lib/utils";

type ReservationOption = { id: string; guestFirstName: string; guestLastName: string; guestPhone: string; covers: number; date: string; timeSlot: string; deposit: number; tableIds: string[]; tables: { id: string; number: string }[] };
type TableOption = { id: string; number: string; capacity: number; zone: string; status: string };
type DishOption = { id: string; name: string; price: number; category: string; categoryOrder: number; order: number };
type Item = { dishId: string; name: string; unitPrice: number; quantity: number; notes: string };

export default function OrderForm({ reservations, tables, dishes, initialReservationId = "" }: { reservations: ReservationOption[]; tables: TableOption[]; dishes: DishOption[]; initialReservationId?: string }) {
  const router = useRouter(); const [loading, setLoading] = useState(false);
  const [reservationId, setReservationId] = useState(initialReservationId); const [tableIds, setTableIds] = useState<string[]>([]); const [covers, setCovers] = useState("2");
  const [guestFirstName, setGuestFirstName] = useState(""); const [guestLastName, setGuestLastName] = useState(""); const [guestPhone, setGuestPhone] = useState(""); const [notes, setNotes] = useState(""); const [items, setItems] = useState<Item[]>([]);
  const reservation = reservations.find((r) => r.id === reservationId);
  const availableTables = tables.filter((table) => !reservation || reservation.tableIds.includes(table.id) || table.status === "AVAILABLE");
  useEffect(() => { if (reservation) { setGuestFirstName(reservation.guestFirstName); setGuestLastName(reservation.guestLastName); setGuestPhone(reservation.guestPhone); setCovers(String(reservation.covers)); setTableIds(reservation.tableIds); } else { setGuestFirstName(""); setGuestLastName(""); setGuestPhone(""); setTableIds([]); setCovers("2"); } }, [reservationId]);
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0), [items]);
  const toggleTable = (id: string) => setTableIds((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  const addDish = (dish: DishOption) => setItems((current) => { const existing = current.find((x) => x.dishId === dish.id); if (existing) return current.map((x) => x.dishId === dish.id ? { ...x, quantity: x.quantity + 1 } : x); return [...current, { dishId: dish.id, name: dish.name, unitPrice: dish.price, quantity: 1, notes: "" }]; });
  const updateQty = (dishId: string, delta: number) => setItems((current) => current.map((x) => x.dishId === dishId ? { ...x, quantity: x.quantity + delta } : x).filter((x) => x.quantity > 0));
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!tableIds.length) { toast.error("Sélectionnez au moins une table."); return; } if (!items.length) { toast.error("Ajoutez au moins un plat."); return; } setLoading(true); try { const create = await fetch("/api/admin/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reservationId: reservationId || undefined, tableIds, covers: Number(covers), guestFirstName, guestLastName, guestPhone, notes }) }); const created = await create.json(); if (!create.ok) throw new Error(created.error); const id = created.data.id; const update = await fetch(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map((x) => ({ dishId: x.dishId, quantity: x.quantity, notes: x.notes })), notes }) }); const updated = await update.json(); if (!update.ok) throw new Error(updated.error); toast.success("Commande créée"); router.push(`/admin/orders/${id}`); router.refresh(); } catch (e) { toast.error(getErrorMessage(e)); } finally { setLoading(false); } };
  return <form onSubmit={save} className="grid grid-cols-1 xl:grid-cols-[1fr_380px] gap-6"><div className="space-y-6"><div className="bg-[#141414] border border-[#222] rounded-xl p-6 space-y-5"><div className="flex items-center gap-2"><UserRound size={18} className="text-[#C8973A]" /><h2 className="font-display text-xl text-[#F5F0EB]">Client & origine</h2></div><Select label="Source de la table" value={reservationId} onChange={(e) => setReservationId(e.target.value)} options={[{ value: "", label: "Arrivée directe sur place" }, ...reservations.map((r) => ({ value: r.id, label: `${r.timeSlot} · ${r.guestFirstName} ${r.guestLastName} · ${r.covers} couverts` }))]} /><div className="grid grid-cols-2 gap-4"><Input label="Prénom" value={guestFirstName} onChange={(e) => setGuestFirstName(e.target.value)} required /><Input label="Nom" value={guestLastName} onChange={(e) => setGuestLastName(e.target.value)} required /></div><Input label="Téléphone" value={guestPhone} onChange={(e) => setGuestPhone(e.target.value)} /><Input label="Couverts" type="number" min="1" max="50" value={covers} onChange={(e) => setCovers(e.target.value)} disabled={!!reservation} /><Textarea label="Notes de service" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Allergies, anniversaire, consignes..." /></div>
    <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><div className="flex items-center gap-2 mb-4"><Armchair size={18} className="text-[#C8973A]" /><h2 className="font-display text-xl text-[#F5F0EB]">Tables</h2></div><p className="text-xs text-[#5A5249] mb-4">{reservation ? "Les tables attribuées à la réservation sont présélectionnées." : "Pour une arrivée directe, seules les tables disponibles peuvent être sélectionnées."}</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{availableTables.map((table) => { const selected = tableIds.includes(table.id); const allowed = reservation ? reservation.tableIds.includes(table.id) : table.status === "AVAILABLE"; return <button type="button" key={table.id} disabled={!allowed} onClick={() => toggleTable(table.id)} className={`text-left rounded-xl border p-3 transition-colors ${selected ? "border-[#C8973A] bg-[#C8973A]/10" : "border-[#222] bg-[#0A0A0A] hover:border-[#333]"} ${!allowed ? "opacity-35 cursor-not-allowed" : ""}`}><p className="text-sm font-medium text-[#F5F0EB]">Table {table.number}</p><p className="text-xs text-[#5A5249] mt-1">{table.capacity} places · {table.zone}</p></button> })}</div></div>
    <div className="bg-[#141414] border border-[#222] rounded-xl p-6"><h2 className="font-display text-xl text-[#F5F0EB] mb-4">Menu</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{dishes.map((dish) => <button type="button" key={dish.id} onClick={() => addDish(dish)} className="text-left p-3 rounded-xl border border-[#222] bg-[#0A0A0A] hover:border-[#C8973A]/40 transition-colors"><div className="flex items-start justify-between gap-2"><div><p className="text-sm text-[#F5F0EB]">{dish.name}</p><p className="text-[11px] text-[#5A5249] mt-1">{dish.category}</p></div><span className="text-sm text-[#C8973A]">{formatPrice(dish.price)}</span></div><span className="inline-flex items-center gap-1 text-xs text-[#5A5249] mt-2"><Plus size={12} /> Ajouter</span></button>)}</div></div></div>
    <div className="bg-[#141414] border border-[#222] rounded-xl p-6 xl:sticky xl:top-6 h-fit"><h2 className="font-display text-xl text-[#F5F0EB] mb-4">Addition</h2>{items.length === 0 ? <p className="text-sm text-[#5A5249] py-8 text-center">Aucun article ajouté.</p> : <div className="space-y-3">{items.map((item) => <div key={item.dishId} className="border-b border-[#222] pb-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-[#F5F0EB]">{item.name}</p><p className="text-xs text-[#5A5249]">{formatPrice(item.unitPrice)} × {item.quantity}</p></div><button type="button" onClick={() => setItems((current) => current.filter((x) => x.dishId !== item.dishId))} className="text-[#5A5249] hover:text-red-400"><Trash2 size={14} /></button></div><div className="flex items-center gap-2 mt-2"><button type="button" onClick={() => updateQty(item.dishId, -1)} className="w-7 h-7 rounded bg-[#222] flex items-center justify-center text-[#9A8F84]"><Minus size={13} /></button><span className="text-xs text-[#F5F0EB] w-6 text-center">{item.quantity}</span><button type="button" onClick={() => updateQty(item.dishId, 1)} className="w-7 h-7 rounded bg-[#222] flex items-center justify-center text-[#9A8F84]"><Plus size={13} /></button></div></div>)}</div>}<div className="border-t border-[#222] mt-5 pt-4 flex items-center justify-between"><span className="text-sm text-[#9A8F84]">Total provisoire</span><span className="font-display text-xl text-[#C8973A]">{formatPrice(subtotal)}</span></div>{reservation?.deposit ? <p className="text-xs text-emerald-400 mt-2">Acompte réservé disponible : {formatPrice(reservation.deposit)}. Il sera imputé automatiquement sur l'addition finale.</p> : <p className="text-xs text-[#5A5249] mt-2">Aucun acompte à déduire : client arrivé directement sur place.</p>}<Button type="submit" loading={loading} className="w-full mt-5">Créer la commande</Button></div></form>;
}
